kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/vcl-frontend
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
trigger:
  event:
    - push
    - pull_request
---
kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/vcl-frontend
      tags:
        - ${DRONE_TAG}
        - stable
trigger:
  event:
    - tag
